# Generated by Django 5.1.6 on 2026-02-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradingCalendar',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='交易日')),
                ('open_time', models.TimeField(verbose_name='开盘时间')),
                ('close_time', models.TimeField(verbose_name='收盘时间')),
                ('is_trading_day', models.BooleanField(default=True, verbose_name='是否交易日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '交易日历',
                'verbose_name_plural': '交易日历',
                'ordering': ['date'],
            },
        ),
    ]
