# Generated by Django 5.1.6 on 2025-02-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpDonwNumber',
            fields=[
                ('trading_date', models.DateField(primary_key=True, serialize=False)),
                ('up_number', models.IntegerField(default=0)),
                ('down_number', models.IntegerField(default=0)),
                ('up_floor_number', models.IntegerField(default=0)),
                ('up_floor_number2', models.IntegerField(default=0)),
                ('down_floor_number', models.IntegerField(default=0)),
                ('floor_explosion_number', models.IntegerField(default=0)),
                ('up_twenty_number', models.IntegerField(default=0)),
                ('up_thirty_number', models.IntegerField(default=0)),
                ('up_fourty_number', models.IntegerField(default=0)),
                ('up_gt_fourty_number', models.IntegerField(default=0)),
            ],
        ),
    ]
