# Generated by Django 5.1.6 on 2025-02-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_emotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updonwnumber',
            name='trading_date',
            field=models.DateField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
