# Generated by Django 5.1.6 on 2025-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_emotion', '0002_alter_updonwnumber_trading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='updonwnumber',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
