# Generated by Django 5.1.6 on 2026-02-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_emotion', '0003_updonwnumber_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updonwnumber',
            name='trading_date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
